from colorama import init #line:1
from termcolor import colored #line:2
from colorama import Fore ,Back ,Style #line:3
init (autoreset =True )#line:4
try :#line:7
    from phone_gen import PhoneNumber #line:8
except :#line:10
    def main ():#line:12
        print ("Installing Module 1")#line:13
        import os #line:14
        import subprocess #line:15
        O0000OO0OOO000O00 ='pip install termcolor'#line:16
        subprocess .call (O0000OO0OOO000O00 ,shell =True ,stdout =subprocess .DEVNULL ,stderr =subprocess .DEVNULL )#line:18
    main ()#line:19
try :#line:21
    from phone_gen import PhoneNumber #line:22
except :#line:24
    def main ():#line:26
        print ("Installing Module 2")#line:27
        import os #line:28
        import subprocess #line:29
        OOOO00O0000O00OOO ='pip install colorama'#line:30
        subprocess .call (OOOO00O0000O00OOO ,shell =True ,stdout =subprocess .DEVNULL ,stderr =subprocess .DEVNULL )#line:32
    main ()#line:33
try :#line:35
    import licensing #line:36
except :#line:38
    def main ():#line:40
        print ("Installing Module 3")#line:41
        import os #line:42
        import subprocess #line:43
        O00O0OO000OOO0000 ='pip install licensing'#line:44
        subprocess .call (O00O0OO000OOO0000 ,shell =True ,stdout =subprocess .DEVNULL ,stderr =subprocess .DEVNULL )#line:46
    main ()#line:47
import sys #line:93
import time #line:94
def typing (OO00000000O0OOOO0 ):#line:96
    for OOOO00O0O0O00OOO0 in OO00000000O0OOOO0 :#line:97
        print (Style .BRIGHT +Fore .RED +OOOO00O0O0O00OOO0 ,end ='',flush =True )#line:98
        time .sleep (.16 )#line:100
def loop ():#line:102
    OOO0OOOOO0000O000 =(Style .BRIGHT +Fore .YELLOW +'We are the Mastering of Dark Code, Our Dark Leads Bot can generate all US Banking Leads.')#line:103
    print (OOO0OOOOO0000O000 )#line:104
    print ('')#line:105
    OOO0OOOOO0000O000 ='CRACKED by @xMarvel_admin'#line:106
    print('''
░░░░░░░░░░░░▄▄▄▄▄▄▄▄▄▄▄▄▄░░░░░░░░░░░░
░░░░░░▄▄████▀▀▀▀▀░░░░░░▀▀█▄▄░░░░░░░░░
░░░▄██▀▀░░░░░░░░░░░░░░░░░░▀██▄░░░░░░░
░░▄█▀░░░░░░░░░░░░░░░░░░░░░░░░▀█▄░░░░░
░██░░░░░░░░░░░░░░░░░░░░░░░░░░░▀█▄░░░░
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▀█▄░░░
██░░░░░░░░░░░░░░░░░░░░░░░░░▄▄▄░░▀█░░░
█░░░░░░░░░░░░░░░░░░░░░░░░░░▀██▄░░██░░
█░░░░░████░░░░░░░░░░░░░░░░░░░░░░░░█▄░
█░░░░░▀▀▀█░░░░░░░░░░░░░░░░░░░░░░░░██░
█░░░░░░░░░░░░░░░░░░░░░░░▄▄▄▄█████▀░█▄
█░░░░░░░░░░▄▄▄▄▄██████▀▀▀▀▀▀░░░░░░░██
█░░░░▄█████▀▀▀▀▀░▄▄▄████░░░░░░░░░░░██
██░░░░░░░░░░░░░░░░▀░░░░░░░░░░░░░░░░██
▀█▄░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█▀
░▀█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▄█░
░░██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██░
░░░██░░░░░░░░░░░░░░░░░░░░░░░░░░░░▄█░░
░░░░▀██▄░░░░░░░░░░░░░░░░░░░░░░▄▄█▀░░░
░░░░░░▀██▄░░░░░░░░░░░░░░░░░▄▄█▀░░░░░░
░░░░░░░░░▀██▄░░░░░░░░░░░▄▄█▀░░░░░░░░░
░░░░░░░░░░░░▀██▄▄▄▄▄▄▄▄█▀░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░█░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░█░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░█░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░█░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░█░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░█░░░░░░░░░░░░░░░░░░

cracked by @xMarvel_official , @xMarvel_admin
    '''
    )
    typing (OOO0OOOOO0000O000 )#line:107
    print ('')#line:108
loop ()#line:110
from hlrcall import hlrfun #line:112
from dl import evilleads #line:113
print ("")#line:115
print (Style .BRIGHT +Fore .CYAN +"Select Option")#line:116
print ("")#line:117
print (Style .BRIGHT +Fore .GREEN +"1. Dark Leads Bot")#line:118
print (Style .BRIGHT +Fore .GREEN +"2. HLR Validation")#line:119
print ("\n")#line:120
print (Style .BRIGHT +Fore .BLUE +"Enter Option : ")#line:121
opts =input ("=> ")#line:123
if opts =="1":#line:124
    evilleads ()#line:125
elif opts =="2":#line:127
    hlrfun ()#line:128
else :#line:130
    print (Style .BRIGHT +Fore .RED +"Wrong option")#line:131
    time .sleep (5 )#line:132
def evilleads ():#line:1
    import os #line:3
    os .system ('cls')#line:4
    try :#line:6
        import pathlib #line:7
    except :#line:9
        def OO00OOO0O00OOO000 ():#line:11
            print ("Installing Module 1")#line:12
            import os #line:14
            import subprocess #line:15
            O0000O00O0000OOO0 ='pip install pathlib'#line:16
            subprocess .call (O0000O00O0000OOO0 ,shell =True ,stdout =subprocess .DEVNULL ,stderr =subprocess .DEVNULL )#line:18
        OO00OOO0O00OOO000 ()#line:19
    try :#line:22
        import phonenumbers #line:23
    except :#line:25
        def OO00OOO0O00OOO000 ():#line:27
            print ("Installing Module 2")#line:28
            import os #line:30
            import subprocess #line:31
            O00O000OO0O0OOO0O ='pip install phonenumbers '#line:32
            subprocess .call (O00O000OO0O0OOO0O ,shell =True ,stdout =subprocess .DEVNULL ,stderr =subprocess .DEVNULL )#line:34
        OO00OOO0O00OOO000 ()#line:35
    try :#line:37
        from phone_gen import PhoneNumber #line:38
    except :#line:40
        def OO00OOO0O00OOO000 ():#line:42
            print ("Installing Module 3")#line:43
            import os #line:44
            import subprocess #line:45
            OOO0OO0O0O0000O00 ='pip install phone-gen'#line:46
            subprocess .call (OOO0OO0O0O0000O00 ,shell =True ,stdout =subprocess .DEVNULL ,stderr =subprocess .DEVNULL )#line:48
        OO00OOO0O00OOO000 ()#line:49
    import random #line:51
    import os ,time #line:52
    import pathlib #line:53
    from phone_gen import PhoneNumber #line:54
    import phonenumbers #line:55
    from phonenumbers import carrier #line:56
    from phonenumbers import timezone #line:57
    from phonenumbers import geocoder #line:58
    from colorama import init #line:59
    from termcolor import colored #line:60
    from colorama import Fore ,Back ,Style #line:61
    init (autoreset =True )#line:62
    def OOO0O00OOO000O0OO ():#line:65
        print ("")#line:66
        print (Style .BRIGHT +Fore .CYAN +"Enter to Generate Number of Leads ")#line:67
        OO0O0000O0OOOOOOO =int (input ("=> "))#line:68
        print (Style .BRIGHT +Fore .GREEN +"Please Wait..While Generating Leads")#line:69
        print ("")#line:70
        def OOOOO0OO0OO000OOO ():#line:72
            O0O00OOOO00O00OOO =[]#line:74
            O000OOOOOO0O00000 ="+1"#line:75
            O0OOOO000O0OOOOOO =['847','309','217','708','312','618','779','630','773','509','360','253','425','206','602','520','480','623','928','225','318','337','504','985','765','463','574','260','219','930','212','315','516','518','585','607','631','716','718','845','914']#line:78
            OOOOOO00OO0OO0OO0 =random .choice (O0OOOO000O0OOOOOO )#line:80
            O0OO0O0O00OO0OOOO =random .randint (1000000 ,9999999 )#line:81
            OOOOOO000OOOOOO0O =str (O000OOOOOO0O00000 )+str (OOOOOO00OO0OO0OO0 )+str (O0OO0O0O00OO0OOOO )#line:82
            OOOO00O0OOOOOO0OO =open ("generate.txt","a")#line:85
            OOOO00O0OOOOOO0OO .writelines (OOOOOO000OOOOOO0O )#line:86
            OOOO00O0OOOOOO0OO .write ("\n")#line:87
            OOOO00O0OOOOOO0OO .close ()#line:88
        for O0O000OOO0000000O in range (OO0O0000O0OOOOOOO ):#line:91
            OOOOO0OO0OO000OOO ()#line:92
    def OO0O00OO00000O0O0 ():#line:94
        print ("")#line:95
        print (Style .BRIGHT +Fore .CYAN +"Enter to Generate Number of Leads ")#line:96
        OOO0OO00O0OO000OO =int (input ("=> "))#line:97
        print (Style .BRIGHT +Fore .GREEN +"Please Wait..While Generating Leads")#line:98
        print ("")#line:99
        def O00000000O00OOOOO ():#line:101
            OOO0O0O0O00O0OO00 =[]#line:103
            O00000O0O0OOO0OO0 ="+1"#line:104
            O0O0OOOO0OOOOO000 =['209','760','805','951','707','310','424','619','408','669','510','415','909','916','949','559','661','541','925','530','831','858','702','725','775','720','970','719','505','575','469','956','409','512','210','817','254','915','430','806','361','830','940','979','325','936','432','612','218','507','952','763','320','651','605','732','908','609','856','201','551','973','862','606','907','250','202','301','703']#line:109
            O0O000O000OOO00O0 =random .choice (O0O0OOOO0OOOOO000 )#line:111
            OOO000O0OO000O00O =random .randint (1000000 ,9999999 )#line:112
            O0OOOO0OO00OOO00O =str (O00000O0O0OOO0OO0 )+str (O0O000O000OOO00O0 )+str (OOO000O0OO000O00O )#line:113
            OO0OOOOO0OOOO0OO0 =open ("generate.txt","a")#line:115
            OO0OOOOO0OOOO0OO0 .writelines (O0OOOO0OO00OOO00O )#line:116
            OO0OOOOO0OOOO0OO0 .write ("\n")#line:117
            OO0OOOOO0OOOO0OO0 .close ()#line:118
        for O0OOO0O0OOOOOO00O in range (OOO0OO00O0OO000OO ):#line:121
            O00000000O00OOOOO ()#line:122
    def O0OOO00OO000OOOO0 ():#line:124
        print ("")#line:125
        print (Style .BRIGHT +Fore .CYAN +"Enter to Generate Number of Leads ")#line:126
        OOO0000OO0000O00O =int (input ("=> "))#line:127
        print (Style .BRIGHT +Fore .GREEN +"Please Wait..While Generating Leads")#line:128
        print ("")#line:129
        def OOO00O0OOOOOO0OO0 ():#line:131
            O00O00OOOO0O000OO =[]#line:133
            OOO000O0O0O0OO0OO ="+1"#line:134
            OOO000OOO000O0OO0 =['205','251','938','334','423','931','615','731','865','901','456','603']#line:135
            OOOO00O00OOO000OO =random .choice (OOO000OOO000O0OO0 )#line:137
            OOO0OO0000OOO0O00 =random .randint (1000000 ,9999999 )#line:138
            O0OOOOOO00000OOOO =str (OOO000O0O0O0OO0OO )+str (OOOO00O00OOO000OO )+str (OOO0OO0000OOO0O00 )#line:139
            O0OO0OO0O0000000O =open ("generate.txt","a")#line:141
            O0OO0OO0O0000000O .writelines (O0OOOOOO00000OOOO )#line:142
            O0OO0OO0O0000000O .write ("\n")#line:143
            O0OO0OO0O0000000O .close ()#line:144
        for OOOOOOOO0OOO00OOO in range (OOO0000OO0000O00O ):#line:147
            OOO00O0OOOOOO0OO0 ()#line:148
    def O0OOOO00OOOOOOOO0 ():#line:150
        print ("")#line:151
        print (Style .BRIGHT +Fore .CYAN +"Enter to Generate Number of Leads ")#line:152
        O0OOOO000O0O0O0OO =int (input ("=> "))#line:153
        print (Style .BRIGHT +Fore .GREEN +"Please Wait..While Generating Leads")#line:154
        print ("")#line:155
        def OOO00O0OO0O000000 ():#line:157
            OO0OOO0OOOO0OOO0O =[]#line:159
            OOOO00O0000000OOO ="+1"#line:160
            O0O000OOOO0000O0O =['937','330','740','614','513','440','216','419','567 ','248','269','616','810','517','313','989','734','231','586','906']#line:162
            OO0O0O0000OO0OOO0 =random .choice (O0O000OOOO0000O0O )#line:164
            O0O0OOOOOOOO000O0 =random .randint (1000000 ,9999999 )#line:165
            O00O0000OO0OOOOOO =str (OOOO00O0000000OOO )+str (OO0O0O0000OO0OOO0 )+str (O0O0OOOOOOOO000O0 )#line:166
            OOOO0O0000O000OOO =open ("generate.txt","a")#line:168
            OOOO0O0000O000OOO .writelines (O00O0000OO0OOOOOO )#line:169
            OOOO0O0000O000OOO .write ("\n")#line:170
            OOOO0O0000O000OOO .close ()#line:171
        for OOO0O00OOOOOO0000 in range (O0OOOO000O0O0O0OO ):#line:174
            OOO00O0OO0O000000 ()#line:175
    def OOO00OOO00O000000 ():#line:177
        print ("")#line:178
        print (Style .BRIGHT +Fore .CYAN +"Enter to Generate Number of Leads")#line:179
        O0000000OO0000000 =int (input ("=> "))#line:180
        print (Style .BRIGHT +Fore .GREEN +"Please Wait..While Generating Leads")#line:181
        print ("")#line:182
        def O0O0O00OO00OO00O0 ():#line:184
            OOO00O00000OO0OOO =[]#line:186
            O0O0OO0O0000O00O0 ="+1"#line:187
            OO0000OOOO0O000OO =['413','978','351','617','781','339','401']#line:188
            O000OOOOOO0OOO000 =random .choice (OO0000OOOO0O000OO )#line:190
            OOO0O0O0O0O000000 =random .randint (1000000 ,9999999 )#line:191
            O0000OO0O00000000 =str (O0O0OO0O0000O00O0 )+str (O000OOOOOO0OOO000 )+str (OOO0O0O0O0O000000 )#line:192
            O0O00000OOO0O0OOO =open ("generate.txt","a")#line:194
            O0O00000OOO0O0OOO .writelines (O0000OO0O00000000 )#line:195
            O0O00000OOO0O0OOO .write ("\n")#line:196
            O0O00000OOO0O0OOO .close ()#line:197
        for OOOOO0000O000O000 in range (O0000000OO0000000 ):#line:200
            O0O0O00OO00OO00O0 ()#line:201
    def OOO00O000O0OOO000 ():#line:203
        print ("")#line:204
        print (Style .BRIGHT +Fore .CYAN +"Enter to Generate Number of Leads ")#line:205
        OO00O0O0OO0O0000O =int (input ("=> "))#line:206
        print (Style .BRIGHT +Fore .GREEN +"Please Wait..While Generating Leads")#line:207
        print ("")#line:208
        def O0000O00O0000O000 ():#line:210
            O00OOO00O0O00000O =[]#line:212
            OO0OO0O000OOOOO0O ="+1"#line:213
            O00O000OO0OOOOOO0 =['515','319','712','563','641','541','208','314','417','816','573','636','660','270','859','606','502']#line:215
            O00OO0OOO00O00O00 =random .choice (O00O000OO0OOOOOO0 )#line:217
            O0O0O00O000O00O0O =random .randint (1000000 ,9999999 )#line:218
            OOOO0000O00OOO0OO =str (OO0OO0O000OOOOO0O )+str (O00OO0OOO00O00O00 )+str (O0O0O00O000O00O0O )#line:219
            OOO0OOOO0O0O0OO0O =open ("generate.txt","a")#line:221
            OOO0OOOO0O0O0OO0O .writelines (OOOO0000O00OOO0OO )#line:222
            OOO0OOOO0O0O0OO0O .write ("\n")#line:223
            OOO0OOOO0O0O0OO0O .close ()#line:224
        for O00OO00OOO00O00O0 in range (OO00O0O0OO0O0000O ):#line:227
            O0000O00O0000O000 ()#line:228
    def OOOOOO0O0O0O0OO00 ():#line:230
        print ("")#line:231
        print (Style .BRIGHT +Fore .CYAN +"Enter to Generate Number of Leads")#line:232
        O00O0O000O0OO0OO0 =int (input ("=> "))#line:233
        print (Style .BRIGHT +Fore .GREEN +"Please Wait..While Generating Leads")#line:234
        print ("")#line:235
        def O0OOO0O00OOOO0O00 ():#line:237
            OO0000OO00OOOO0OO =[]#line:239
            O000O00OO00OO0000 ="+1"#line:240
            OOOO000OO0O000O00 =['610','570','814','724','240','412','878']#line:241
            OO0000OOO00O0000O =random .choice (OOOO000OO0O000O00 )#line:243
            OOOO00OOOOO0OO0OO =random .randint (1000000 ,9999999 )#line:244
            OOOO0000O0000OOOO =str (O000O00OO00OO0000 )+str (OO0000OOO00O0000O )+str (OOOO00OOOOO0OO0OO )#line:245
            OOOO000O00OOO00OO =open ("generate.txt","a")#line:247
            OOOO000O00OOO00OO .writelines (OOOO0000O0000OOOO )#line:248
            OOOO000O00OOO00OO .write ("\n")#line:249
            OOOO000O00OOO00OO .close ()#line:250
        for O0OO0OO0OO000OO00 in range (O00O0O000O0OO0OO0 ):#line:253
            O0OOO0O00OOOO0O00 ()#line:254
    def O0000OO00O00O0OO0 ():#line:256
        print ("")#line:257
        print (Style .BRIGHT +Fore .CYAN +"Enter to Generate Number of Leads")#line:258
        O00OOOOOOO0O00OOO =int (input ("=> "))#line:259
        print (Style .BRIGHT +Fore .GREEN +"Please Wait..While Generating Leads")#line:260
        print ("")#line:261
        def OO0000OO0O0000000 ():#line:263
            OOOOOOO0000OO0OO0 =[]#line:265
            OOOOOO000O000O00O ="+1"#line:266
            OO00OOO0OOOOO0OOO =['803','843','864']#line:267
            O0OO00O00000O000O =random .choice (OO00OOO0OOOOO0OOO )#line:269
            O0O000O00O0O00OO0 =random .randint (1000000 ,9999999 )#line:270
            OOOO0O0OOO0O0OO00 =str (OOOOOO000O000O00O )+str (O0OO00O00000O000O )+str (O0O000O00O0O00OO0 )#line:271
            OOO0000OOOOO00OOO =open ("generate.txt","a")#line:273
            OOO0000OOOOO00OOO .writelines (OOOO0O0OOO0O0OO00 )#line:274
            OOO0000OOOOO00OOO .write ("\n")#line:275
            OOO0000OOOOO00OOO .close ()#line:276
        for OO00OOO000O0O0000 in range (O00OOOOOOO0O00OOO ):#line:279
            OO0000OO0O0000000 ()#line:280
    def OO000000000O0OO00 ():#line:282
        print ("")#line:283
        print (Style .BRIGHT +Fore .CYAN +"Enter to Generate Number of Leads")#line:284
        OOOOOOO0OO000O000 =int (input ("=> "))#line:285
        print (Style .BRIGHT +Fore .GREEN +"Please Wait..While Generating Leads")#line:286
        print ("")#line:287
        def O0O0O00OO0O000O0O ():#line:289
            OO0O0OOOO0O000000 =[]#line:291
            OOOOOOO0OO0OO0O0O ="+1"#line:292
            O0OOOOOOOOO000OOO =['336','910','252','828','919','984','704']#line:293
            O00000O0O0O00OOOO =random .choice (O0OOOOOOOOO000OOO )#line:295
            O000OO0O0O00OO00O =random .randint (1000000 ,9999999 )#line:296
            O00000OO00OO00000 =str (OOOOOOO0OO0OO0O0O )+str (O00000O0O0O00OOOO )+str (O000OO0O0O00OO00O )#line:297
            OO00000O0OO0O00O0 =open ("generate.txt","a")#line:299
            OO00000O0OO0O00O0 .writelines (O00000OO00OO00000 )#line:300
            OO00000O0OO0O00O0 .write ("\n")#line:301
            OO00000O0OO0O00O0 .close ()#line:302
        for OOO00OOO0O00000O0 in range (OOOOOOO0OO000O000 ):#line:305
            O0O0O00OO0O000O0O ()#line:306
    def OOOO0OO000O00OO00 ():#line:308
        print ("")#line:309
        print (Style .BRIGHT +Fore .CYAN +"Enter to Generate Number of Leads ")#line:310
        OOO0OOOOO0OO00O00 =int (input ("=> "))#line:311
        print (Style .BRIGHT +Fore .GREEN +"Please Wait..While Generating Leads")#line:312
        print ("")#line:313
        def OO00OOO0OOOO0OO0O ():#line:315
            OOO0OOO00O0O00OO0 =[]#line:317
            OOOO000OOOO000O00 ="+1"#line:318
            OOO0OO00OOO0O0000 ='302'#line:319
            OO0O000OO00OOO0OO =random .randint (1000000 ,9999999 )#line:320
            OOOO0OOO000O000OO =str (OOOO000OOOO000O00 )+str (OOO0OO00OOO0O0000 )+str (OO0O000OO00OOO0OO )#line:321
            O0OO0000OO0O0O0O0 =open ("generate.txt","a")#line:323
            O0OO0000OO0O0O0O0 .writelines (OOOO0OOO000O000OO )#line:324
            O0OO0000OO0O0O0O0 .write ("\n")#line:325
            O0OO0000OO0O0O0O0 .close ()#line:326
        for OO0OO0OO0OOO000O0 in range (OOO0OOOOO0OO00O00 ):#line:329
            OO00OOO0OOOO0OO0O ()#line:330
    def O0OOOO0OO000O0O0O ():#line:333
        if os .path .exists ("generate.txt"):#line:335
            os .remove ("generate.txt")#line:336
        if os .path .exists ("invalid_number.txt"):#line:338
            os .remove ("invalid_number.txt")#line:339
        print (Style .BRIGHT +Fore .BLUE +"Select Bank")#line:341
        time .sleep (0.5 )#line:342
        print ("")#line:343
        print (Style .BRIGHT +Fore .GREEN +"1. Chase Bank")#line:344
        time .sleep (0.5 )#line:345
        print (Style .BRIGHT +Fore .GREEN +"2. Wells Fargo")#line:346
        time .sleep (0.5 )#line:347
        print (Style .BRIGHT +Fore .GREEN +"3. Region Bank")#line:348
        time .sleep (0.5 )#line:349
        print (Style .BRIGHT +Fore .GREEN +"4. Huntington Bank")#line:350
        time .sleep (0.5 )#line:351
        print (Style .BRIGHT +Fore .GREEN +"5. Citizen Bank")#line:352
        time .sleep (0.5 )#line:353
        print (Style .BRIGHT +Fore .GREEN +"6. US Bank")#line:354
        time .sleep (0.5 )#line:355
        print (Style .BRIGHT +Fore .GREEN +"7. PNC Bank")#line:356
        time .sleep (0.5 )#line:357
        print (Style .BRIGHT +Fore .GREEN +"8. First Citizen Bank")#line:358
        time .sleep (0.5 )#line:359
        print (Style .BRIGHT +Fore .GREEN +"9. Bank of America")#line:360
        time .sleep (0.5 )#line:361
        print (Style .BRIGHT +Fore .GREEN +"10. M&T Bank")#line:362
        time .sleep (0.5 )#line:363
        print ("")#line:365
        print (Style .BRIGHT +Fore .YELLOW +"Enter Option ")#line:366
        OO0OOO000OOOOOO00 =input ("=> ")#line:367
        if OO0OOO000OOOOOO00 =="1":#line:369
            OOO0O00OOO000O0OO ()#line:370
        elif OO0OOO000OOOOOO00 =="2":#line:372
            OO0O00OO00000O0O0 ()#line:373
        elif OO0OOO000OOOOOO00 =="3":#line:375
            O0OOO00OO000OOOO0 ()#line:376
        elif OO0OOO000OOOOOO00 =="4":#line:378
            O0OOOO00OOOOOOOO0 ()#line:379
        elif OO0OOO000OOOOOO00 =="5":#line:381
            OOO00OOO00O000000 ()#line:382
        elif OO0OOO000OOOOOO00 =="6":#line:384
            OOO00O000O0OOO000 ()#line:385
        elif OO0OOO000OOOOOO00 =="7":#line:387
            OOOOOO0O0O0O0OO00 ()#line:388
        elif OO0OOO000OOOOOO00 =="8":#line:390
            O0000OO00O00O0OO0 ()#line:391
        elif OO0OOO000OOOOOO00 =="9":#line:393
            OO000000000O0OO00 ()#line:394
        elif OO0OOO000OOOOOO00 =="10":#line:396
            OOOO0OO000O00OO00 ()#line:397
        else :#line:399
            print (Style .BRIGHT +Fore .RED +"Wrong Option.Please Enter Valid Option")#line:400
            time .sleep (1 )#line:401
            return O0OOOO0OO000O0O0O ()#line:402
    O0OOOO0OO000O0O0O ()#line:404
    def OO00O0O0O000O00OO ():#line:406
        print ("")#line:408
        print (Style .BRIGHT +Fore .BLUE +"Enter Filename to Save it.(demo.txt)")#line:409
        OO000000OO0O000O0 =input ("=> ")#line:410
        print ("")#line:411
        print (Style .BRIGHT +Fore .GREEN +"Please Wait..While Validating Leads")#line:412
        O0OOOO00OO0OO0000 =open ("generate.txt","r")#line:413
        while True :#line:415
            O0O00OOOOOOO0O0OO =O0OOOO00OO0OO0000 .readline ()#line:416
            if not O0O00OOOOOOO0O0OO :#line:418
                break #line:419
            OOO00OOO0OO00O00O =phonenumbers .parse (O0O00OOOOOOO0O0OO ,None )#line:421
            O0O00000OO0OOO000 =geocoder .description_for_number (OOO00OOO0OO00O00O ,None )#line:422
            if not O0O00000OO0OOO000 :#line:424
                OO00OO0O0O0000O00 =O0O00OOOOOOO0O0OO #line:425
                OO0O00O00O0O00000 =open ('invalid_leads.txt',"a")#line:426
                OO0O00O00O0O00000 .writelines (OO00OO0O0O0000O00 )#line:427
                OO0O00O00O0O00000 .close ()#line:428
            else :#line:429
                O0O0OO0O00OOOO00O =O0O00OOOOOOO0O0OO #line:430
                OO0O00O00O0O00000 =open (OO000000OO0O000O0 ,"a")#line:431
                OO0O00O00O0O00000 .writelines (O0O0OO0O00OOOO00O )#line:432
                OO0O00O00O0O00000 .close ()#line:433
        print ("")#line:435
        print (Style .BRIGHT +Fore .YELLOW +"Leads are Generate and Validate Successfully")#line:436
        print ("")#line:437
        OO0O00O00O0O00000 =open (OO000000OO0O000O0 ,"r")#line:439
        OOOOO00O0OO0OOOOO =0 #line:440
        O0OOO0000O00O0O0O =OO0O00O00O0O00000 .read ()#line:441
        O00OOO0O0O00O0OO0 =O0OOO0000O00O0O0O .split ("\n")#line:442
        for OOO000O00O0O00OO0 in O00OOO0O0O00O0OO0 :#line:444
            if OOO000O00O0O00OO0 :#line:445
                OOOOO00O0OO0OOOOO +=1 #line:446
        O0OOO0OO0O000000O =OOOOO00O0OO0OOOOO #line:447
        time .sleep (1 )#line:449
        O0OOOO00OO0OO0000 .close ()#line:450
        os .remove ('generate.txt')#line:451
        print (Style .BRIGHT +Fore .CYAN +f"Valid {O0OOO0OO0O000000O} Leads are saved in {OO000000OO0O000O0}")#line:454
        print ("")#line:455
        print (Style .BRIGHT +Fore .RED +f"Invalid Leads are saved in Invalid_leads.txt")#line:456
        print ("\n")#line:457
    OO00O0O0O000O00OO ()#line:458
    O0O0OOO0O00OO0OOO =input ("Press Enter to Exit.")#line:460
    O0O0OOO0O00OO0OOO =input ("Press Enter to Exit.")#line:461
    O0O0OOO0O00OO0OOO =input ("Press Enter to Exit.")#line:462
def hlrfun ():#line:1
    import requests #line:2
    import json #line:3
    import sys #line:4
    import requests ,sys #line:5
    import os ,time #line:6
    from itertools import islice #line:7
    import threading #line:8
    from bs4 import BeautifulSoup #line:9
    import pathlib #line:10
    from colorama import init #line:11
    from termcolor import colored #line:12
    from colorama import Fore ,Back ,Style #line:13
    init (autoreset =True )#line:14
    import shutil #line:15
    from t1 import tel1 #line:17
    from t2 import tel2 #line:18
    from t3 import tel3 #line:19
    from t4 import tel4 #line:20
    from urllib import request #line:21
    os .system ('cls')#line:24
    try :#line:26
        import pathlib #line:27
    except :#line:29
        def O0O0O0O000OO0OOOO ():#line:31
            print ("Installing Module 1")#line:32
            import os #line:34
            import subprocess #line:35
            O0OO000000OO00000 ='pip install pathlib'#line:36
            subprocess .call (O0OO000000OO00000 ,shell =True ,stdout =subprocess .DEVNULL ,stderr =subprocess .DEVNULL )#line:38
        O0O0O0O000OO0OOOO ()#line:39
    try :#line:41
        from bs4 import BeautifulSoup #line:42
    except :#line:44
        def O0O0O0O000OO0OOOO ():#line:46
            print ("Installing Module 2")#line:47
            import os #line:49
            import subprocess #line:50
            OOOO00O00000O00O0 ='pip install beautifulsoup4'#line:51
            OO000OO000O0O00O0 ='pip install lxml'#line:52
            subprocess .call (OOOO00O00000O00O0 ,shell =True ,stdout =subprocess .DEVNULL ,stderr =subprocess .DEVNULL )#line:54
            subprocess .call (OO000OO000O0O00O0 ,shell =True ,stdout =subprocess .DEVNULL ,stderr =subprocess .DEVNULL )#line:56
        O0O0O0O000OO0OOOO ()#line:57
    try :#line:59
        from colorama import Fore ,Back ,Style #line:60
    except :#line:62
        def O0O0O0O000OO0OOOO ():#line:64
            print ("Installing Module 3")#line:65
            import os #line:67
            import subprocess #line:68
            OO00OO0O0OOO0O0OO ='pip install colorama'#line:69
            subprocess .call (OO00OO0O0OOO0O0OO ,shell =True ,stdout =subprocess .DEVNULL ,stderr =subprocess .DEVNULL )#line:71
        O0O0O0O000OO0OOOO ()#line:72
    try :#line:74
        from termcolor import colored #line:75
    except :#line:77
        def O0O0O0O000OO0OOOO ():#line:79
            print ("Installing Module 4")#line:80
            import os #line:82
            import subprocess #line:83
            O0OOO0000000OO0O0 ='pip install termcolor'#line:84
            subprocess .call (O0OOO0000000OO0O0 ,shell =True ,stdout =subprocess .DEVNULL ,stderr =subprocess .DEVNULL )#line:86
        O0O0O0O000OO0OOOO ()#line:87
    try :#line:89
        import requests #line:90
    except :#line:92
        def O0O0O0O000OO0OOOO ():#line:94
            print ("Installing Module 5")#line:95
            import os #line:97
            import subprocess #line:98
            O0000O0O0000O000O ='pip install requests'#line:99
            subprocess .call (O0000O0O0000O000O ,shell =True ,stdout =subprocess .DEVNULL ,stderr =subprocess .DEVNULL )#line:101
        O0O0O0O000OO0OOOO ()#line:102
    if os .path .exists ('cache'):#line:105
        shutil .rmtree ('cache')#line:106
    if os .path .exists ('DL Proxy'):#line:108
        shutil .rmtree ('DL Proxy')#line:109
    if os .path .exists ('dl_proxy.txt'):#line:111
        os .remove ('dl_proxy.txt')#line:112
    print (Style .BRIGHT +Fore .CYAN +"Lookup Your Leads via Valid Proxy Only..")#line:114
    print ("")#line:115
    print (Style .BRIGHT +Fore .BLUE +"All the results are saved in HLR Lookup Folder")#line:116
    print ("\n")#line:117
    def O0O00O00OOOO0O0O0 ():#line:119
        try :#line:120
            print (Style .BRIGHT +Fore .YELLOW +"Enter Filename(demo.txt) : ")#line:121
            O0O0O00OOO00OOO0O =input ("=> ")#line:122
            def O0O000O0OO0OOOO00 (OOO0O0OOOO0O000O0 ,even =True ):#line:124
                for OOOO0O0OOOO0OOOOO in OOO0O0OOOO0O000O0 :#line:125
                    yield even ,OOOO0O0OOOO0OOOOO #line:126
                    even =not even #line:127
            with open (O0O0O00OOO00OOO0O )as O00OO00OO0O0000O0 ,open ("ff_1.txt","w")as OO0000OO0OO000OO0 ,open ("ff_2.txt","w")as O0OOO0000O0O0O0O0 :#line:132
                for O0OO0OOOO00O00O0O ,O0OO0O00OOO0OO00O in O0O000O0OO0OOOO00 (O00OO00OO0O0000O0 ):#line:133
                    if O0OO0OOOO00O00O0O :#line:134
                        O0OOO0000O0O0O0O0 .write (O0OO0O00OOO0OO00O )#line:135
                    else :#line:136
                        OO0000OO0OO000OO0 .write (O0OO0O00OOO0OO00O )#line:137
            with open ("ff_1.txt")as O00OO00OO0O0000O0 ,open ("fn_1.txt","w")as OO0000OO0OO000OO0 ,open ("fn_2.txt","w")as O0OOO0000O0O0O0O0 :#line:142
                for O0OO0OOOO00O00O0O ,O0OO0O00OOO0OO00O in O0O000O0OO0OOOO00 (O00OO00OO0O0000O0 ):#line:143
                    if O0OO0OOOO00O00O0O :#line:144
                        O0OOO0000O0O0O0O0 .write (O0OO0O00OOO0OO00O )#line:145
                    else :#line:146
                        OO0000OO0OO000OO0 .write (O0OO0O00OOO0OO00O )#line:147
            with open ("ff_2.txt")as O00OO00OO0O0000O0 ,open ("fn_3.txt","w")as OO0000OO0OO000OO0 ,open ("fn_4.txt","w")as O0OOO0000O0O0O0O0 :#line:153
                for O0OO0OOOO00O00O0O ,O0OO0O00OOO0OO00O in O0O000O0OO0OOOO00 (O00OO00OO0O0000O0 ):#line:154
                    if O0OO0OOOO00O00O0O :#line:155
                        O0OOO0000O0O0O0O0 .write (O0OO0O00OOO0OO00O )#line:156
                    else :#line:157
                        OO0000OO0OO000OO0 .write (O0OO0O00OOO0OO00O )#line:158
            OOO0O0OO00O00000O =os .getcwd ()#line:161
            OO00O0O0O000O0OOO =pathlib .Path (OOO0O0OO00O00000O ,"cache")#line:162
            OO00O0O0O000O0OOO .mkdir (parents =True ,exist_ok =True )#line:163
            OO00OO0OOOOO000OO =os .getcwd ()#line:165
            O00O000O0O000OOO0 =os .path .join (OO00OO0OOOOO000OO ,"fn_1.txt")#line:166
            OO00O0000000O00O0 =os .path .join (OO00OO0OOOOO000OO ,"fn_2.txt")#line:167
            OO00000OOOO0O0O0O =os .path .join (OO00OO0OOOOO000OO ,"fn_3.txt")#line:168
            OOO0OOOOOOOOO00O0 =os .path .join (OO00OO0OOOOO000OO ,"fn_4.txt")#line:169
            OO00O000O0O00O000 =os .path .join (OO00OO0OOOOO000OO ,"cache","fn_1.txt")#line:171
            O0O0OOO00OO0O0OO0 =os .path .join (OO00OO0OOOOO000OO ,"cache","fn_2.txt")#line:172
            O0O00O000O0OO0OOO =os .path .join (OO00OO0OOOOO000OO ,"cache","fn_3.txt")#line:173
            O0OOOOOO0OOO00OOO =os .path .join (OO00OO0OOOOO000OO ,"cache","fn_4.txt")#line:174
            shutil .move (O00O000O0O000OOO0 ,OO00O000O0O00O000 )#line:176
            shutil .move (OO00O0000000O00O0 ,O0O0OOO00OO0O0OO0 )#line:177
            shutil .move (OO00000OOOO0O0O0O ,O0O00O000O0OO0OOO )#line:178
            shutil .move (OOO0OOOOOOOOO00O0 ,O0OOOOOO0OOO00OOO )#line:179
            os .remove ("ff_1.txt")#line:182
            os .remove ("ff_2.txt")#line:183
        except :#line:185
            print (Style .BRIGHT +Fore .RED +"File Not Found "+O0O0O00OOO00OOO0O )#line:186
            print (Style .BRIGHT +Fore .BLUE +"Please add your file in Currenct Directory or Check your Filename with .txt extension")#line:187
            print ("")#line:188
            return O0O00O00OOOO0O0O0 ()#line:189
    O0O00O00OOOO0O0O0 ()#line:191
    OOO00O00O000OOOO0 ='https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all'#line:193
    OO000OO00OO0OOO0O ='dl_proxy.txt'#line:195
    request .urlretrieve (OOO00O00O000OOOO0 ,OO000OO00OO0OOO0O )#line:197
    def OOOOOO00O0OO000OO ():#line:199
        O0000OOO00OO0O00O ="dl_proxy.txt"#line:201
        def O0O00000OOO0O0O00 (OO0OO00OO0O0OO00O ,even =True ):#line:203
            for O0O00OOO0O0O00OO0 in OO0OO00OO0O0OO00O :#line:204
                yield even ,O0O00OOO0O0O00OO0 #line:205
                even =not even #line:206
        with open (O0000OOO00OO0O00O )as OOOOOO000O000O0O0 ,open ("pr_1.txt","w")as OO0O000OOOO0000OO ,open ("pr_2.txt","w")as OOOO0O0OO0O000O0O :#line:211
            for OO000O0000O0OOOO0 ,O0000OOOOO0O0000O in O0O00000OOO0O0O00 (OOOOOO000O000O0O0 ):#line:212
                if OO000O0000O0OOOO0 :#line:213
                    OOOO0O0OO0O000O0O .write (O0000OOOOO0O0000O )#line:214
                else :#line:215
                    OO0O000OOOO0000OO .write (O0000OOOOO0O0000O )#line:216
        with open ("pr_1.txt")as OOOOOO000O000O0O0 ,open ("ec1.txt","w")as OO0O000OOOO0000OO ,open ("ec2.txt","w")as OOOO0O0OO0O000O0O :#line:221
            for OO000O0000O0OOOO0 ,O0000OOOOO0O0000O in O0O00000OOO0O0O00 (OOOOOO000O000O0O0 ):#line:222
                if OO000O0000O0OOOO0 :#line:223
                    OOOO0O0OO0O000O0O .write (O0000OOOOO0O0000O )#line:224
                else :#line:225
                    OO0O000OOOO0000OO .write (O0000OOOOO0O0000O )#line:226
        with open ("pr_2.txt")as OOOOOO000O000O0O0 ,open ("ec3.txt","w")as OO0O000OOOO0000OO ,open ("ec4.txt","w")as OOOO0O0OO0O000O0O :#line:232
            for OO000O0000O0OOOO0 ,O0000OOOOO0O0000O in O0O00000OOO0O0O00 (OOOOOO000O000O0O0 ):#line:233
                if OO000O0000O0OOOO0 :#line:234
                    OOOO0O0OO0O000O0O .write (O0000OOOOO0O0000O )#line:235
                else :#line:236
                    OO0O000OOOO0000OO .write (O0000OOOOO0O0000O )#line:237
        os .remove ("pr_1.txt")#line:239
        os .remove ("pr_2.txt")#line:240
        os .remove ("dl_proxy.txt")#line:241
        OO0O00O000OOOO000 =os .getcwd ()#line:243
        OOO0O0OO0O000O0O0 =pathlib .Path (OO0O00O000OOOO000 ,"DL Proxy")#line:244
        OOO0O0OO0O000O0O0 .mkdir (parents =True ,exist_ok =True )#line:245
        O00OOO00O0O0O00O0 =os .getcwd ()#line:247
        OO0OOOO0OO0OO00OO =os .path .join (O00OOO00O0O0O00O0 ,"ec1.txt")#line:248
        O00000O0O00OO0OO0 =os .path .join (O00OOO00O0O0O00O0 ,"ec2.txt")#line:249
        O000OOO00O00OOO00 =os .path .join (O00OOO00O0O0O00O0 ,"ec3.txt")#line:250
        O000000O0OOOO0000 =os .path .join (O00OOO00O0O0O00O0 ,"ec4.txt")#line:251
        O00O0O0O0000O00O0 =os .path .join (O00OOO00O0O0O00O0 ,"DL Proxy","ec1.txt")#line:253
        OOOO00OOOOOO0OOOO =os .path .join (O00OOO00O0O0O00O0 ,"DL Proxy","ec2.txt")#line:254
        OO0000O0OOOOO0000 =os .path .join (O00OOO00O0O0O00O0 ,"DL Proxy","ec3.txt")#line:255
        O0O000OO000O0OO00 =os .path .join (O00OOO00O0O0O00O0 ,"DL Proxy","ec4.txt")#line:256
        shutil .move (OO0OOOO0OO0OO00OO ,O00O0O0O0000O00O0 )#line:258
        shutil .move (O00000O0O00OO0OO0 ,OOOO00OOOOOO0OOOO )#line:259
        shutil .move (O000OOO00O00OOO00 ,OO0000O0OOOOO0000 )#line:260
        shutil .move (O000000O0OOOO0000 ,O0O000OO000O0OO00 )#line:261
def tel1 ():#line:16
    OO00000O0OO0O0O00 =open ("./cache/"+"fn_1.txt","r")#line:19
    OO0OOO000OO0OOO0O =os .getcwd ()#line:20
    OO0O0000OOO0O000O =pathlib .Path (OO0OOO000OO0OOO0O ,"HLR Lookup")#line:21
    OO0O0000OOO0O000O .mkdir (parents =True ,exist_ok =True )#line:22
    def O0000O0OOOO000O00 ():#line:26
        O0OO000000O0O0OOO =open ("./DL Proxy/"+"ec1.txt","r")#line:28
        while True :#line:30
            OOOOOO0OOOO00OOOO =O0OO000000O0O0OOO .readline ()#line:31
            if not OOOOOO0OOOO00OOOO :#line:33
                O0OO000000O0O0OOO .close ()#line:34
                time .sleep (1 )#line:35
                print ("Please Wait..Generating Proxy")#line:36
                prxgen ()#line:37
                time .sleep (20 )#line:38
                return O0000O0OOOO000O00 ()#line:39
            try :#line:42
                OOO0O0000O0O00OO0 =f'http://{OOOOOO0OOOO00OOOO}'#line:44
                OOO0OO0OOO0O0O00O ='https://ipecho.net/plain/'#line:45
                O0O000O000O0OO00O =requests .get (OOO0OO0OOO0O0O00O ,proxies ={"http":OOO0O0000O0O00OO0 ,"https":OOO0O0000O0O00OO0 },timeout =3 )#line:47
                time .sleep (0.5 )#line:48
                OOO00OO000O0000O0 =requests .get (OOO0OO0OOO0O0O00O ,proxies ={"http":OOO0O0000O0O00OO0 ,"https":OOO0O0000O0O00OO0 },timeout =3 )#line:49
                print (Style .BRIGHT +Fore .GREEN +"Valid Proxy Address : ",OOO00OO000O0000O0 .text )#line:50
                for O000OO0O0O000000O in range (10 ):#line:52
                    OOOO0O000000O000O =OO00000O0OO0O0O00 .readline ()#line:53
                    if not OOOO0O000000O000O :#line:56
                        OO0OO000O0O0OOO0O =input ("Enter : ")#line:58
                        OO0OO000O0O0OOO0O =input ("Enter : ")#line:59
                        break #line:60
                    OOO0OO0OOO0O0O00O =f'https://api.telnyx.com/anonymous/v2/number_lookup/{OOOO0O000000O000O}'#line:62
                    OO0OO0OO00OO0O0O0 =requests .get (OOO0OO0OOO0O0O00O )#line:63
                    OOOO00O0OOOOO0OO0 =OO0OO0OO00OO0O0O0 .json ()#line:64
                    print (Style .BRIGHT +Fore .YELLOW +OOOO00O0OOOOO0OO0 ['data']['carrier']['name'])#line:66
                    OOOO0OOOOO0OO0O0O =OOOO00O0OOOOO0OO0 ['data']['carrier']['name']#line:68
                    O00O0O00000000O00 =OOOO00O0OOOOO0OO0 ['data']['carrier']['name']#line:69
                    if not OOOO0OOOOO0OO0O0O =="":#line:71
                        O0O000O0OO0OO00O0 =O00O0O00000000O00 +".txt"#line:72
                        O0O0000O000O0O0OO =OO0O0000OOO0O000O /O0O000O0OO0OO00O0 #line:73
                        OOO0OO0OO0000O000 =open (O0O0000O000O0O0OO ,"a")#line:74
                        OOO0OO0OO0000O000 .writelines (OOOO0O000000O000O )#line:75
                        OOO0OO0OO0000O000 .close ()#line:76
                    elif OOOO0OOOOO0OO0O0O =="":#line:78
                        OOOO0O000O0O00O0O ="Invalid_numbers.txt"#line:79
                        O0O0000O000O0O0OO =OO0O0000OOO0O000O /OOOO0O000O0O00O0O #line:80
                        OOO0OO0OO0000O000 =open (O0O0000O000O0O0OO ,"a")#line:81
                        OOO0OO0OO0000O000 .writelines (OOOO0O000000O000O )#line:82
                        OOO0OO0OO0000O000 .close ()#line:83
                    else :#line:85
                        print ("Invalid Number")#line:86
            except :#line:88
                print (Style .BRIGHT +Fore .RED +"Invalid Proxy "+OOOOOO0OOOO00OOOO )#line:89
    O0000O0OOOO000O00 ()#line:92
    tel1()
    OOOOOO00O0OO000OO ()#line:263
    OOOOO0000000O0O00 =threading .Thread (target =tel1 ,args =())#line:268
    OOOOO0000000O0O00 .start ()#line:269
    time .sleep (3 )#line:270
    O00OO00OOO000000O =threading .Thread (target =tel2 ,args =())#line:271
    O00OO00OOO000000O .start ()#line:272
    time .sleep (5 )#line:273
    OOOOO0000000O0O00 =threading .Thread (target =tel3 ,args =())#line:274
    OOOOO0000000O0O00 .start ()#line:275
    time .sleep (8 )#line:276
    O00OO00OOO000000O =threading .Thread (target =tel4 ,args =())#line:277
    O00OO00OOO000000O .start ()#line:278
import os ,time ,sys ,subprocess #line:1
import shutil #line:2
from urllib import request #line:3
def prxgen ():#line:6
    if os .path .exists ('DL Proxy'):#line:7
        shutil .rmtree ('DL Proxy')#line:8
    time .sleep (1 )#line:10
    O00OO00O0OOOOO0O0 ='https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all'#line:11
    O0000O0OO0O0OOO0O ='dl_proxy.txt'#line:13
    request .urlretrieve (O00OO00O0OOOOO0O0 ,O0000O0OO0O0OOO0O )#line:15
    time .sleep (1 )#line:17
    OOO00O00O0000OOO0 ="dl_proxy.txt"#line:19
    def O0OO0O00OO00OOOOO (O00OO000OO00O0OOO ,even =True ):#line:21
        for O0O00OOO0000O000O in O00OO000OO00O0OOO :#line:22
            yield even ,O0O00OOO0000O000O #line:23
            even =not even #line:24
    with open (OOO00O00O0000OOO0 )as OOO0O00O0OOO0OO00 ,open ("pr_1.txt","w")as OO00000O000000000 ,open ("pr_2.txt","w")as O0OO0000O0O0OOO00 :#line:29
        for OOO0OOOOO0O0O0OOO ,OOO0O00OO0O00OO00 in O0OO0O00OO00OOOOO (OOO0O00O0OOO0OO00 ):#line:30
            if OOO0OOOOO0O0O0OOO :#line:31
                O0OO0000O0O0OOO00 .write (OOO0O00OO0O00OO00 )#line:32
            else :#line:33
                OO00000O000000000 .write (OOO0O00OO0O00OO00 )#line:34
    with open ("pr_1.txt")as OOO0O00O0OOO0OO00 ,open ("ec1.txt","w")as OO00000O000000000 ,open ("ec2.txt","w")as O0OO0000O0O0OOO00 :#line:39
        for OOO0OOOOO0O0O0OOO ,OOO0O00OO0O00OO00 in O0OO0O00OO00OOOOO (OOO0O00O0OOO0OO00 ):#line:41
            if OOO0OOOOO0O0O0OOO :#line:42
                O0OO0000O0O0OOO00 .write (OOO0O00OO0O00OO00 )#line:43
            else :#line:44
                OO00000O000000000 .write (OOO0O00OO0O00OO00 )#line:45
    with open ("pr_2.txt")as OOO0O00O0OOO0OO00 ,open ("ec3.txt","w")as OO00000O000000000 ,open ("ec4.txt","w")as O0OO0000O0O0OOO00 :#line:49
        for OOO0OOOOO0O0O0OOO ,OOO0O00OO0O00OO00 in O0OO0O00OO00OOOOO (OOO0O00O0OOO0OO00 ):#line:50
            if OOO0OOOOO0O0O0OOO :#line:51
                O0OO0000O0O0OOO00 .write (OOO0O00OO0O00OO00 )#line:52
            else :#line:53
                OO00000O000000000 .write (OOO0O00OO0O00OO00 )#line:54
    os .remove ("pr_1.txt")#line:56
    os .remove ("pr_2.txt")#line:57
    os .remove ("dl_proxy.txt")#line:58
    O0O0O00OO0OO000OO =os .getcwd ()#line:60
    OOOOO0000O0O00OOO =pathlib .Path (O0O0O00OO0OO000OO ,"DL Proxy")#line:61
    OOOOO0000O0O00OOO .mkdir (parents =True ,exist_ok =True )#line:62
    OOO0O00OOO00OO000 =os .getcwd ()#line:64
    OOO0OOO0O0OOO00O0 =os .path .join (OOO0O00OOO00OO000 ,"ec1.txt")#line:65
    OOO0OO0OOOO0O0OOO =os .path .join (OOO0O00OOO00OO000 ,"ec2.txt")#line:66
    OO0O000O0OO00OOO0 =os .path .join (OOO0O00OOO00OO000 ,"ec3.txt")#line:67
    OO0OOO0000OOOOO0O =os .path .join (OOO0O00OOO00OO000 ,"ec4.txt")#line:68
    OOOO0000O0OO000OO =os .path .join (OOO0O00OOO00OO000 ,"DL Proxy","ec1.txt")#line:70
    O0O00O00O00O0OOO0 =os .path .join (OOO0O00OOO00OO000 ,"DL Proxy","ec2.txt")#line:71
    O00O00O000O000000 =os .path .join (OOO0O00OOO00OO000 ,"DL Proxy","ec3.txt")#line:72
    OO0OOO0O0O0000O0O =os .path .join (OOO0O00OOO00OO000 ,"DL Proxy","ec4.txt")#line:73
    shutil .move (OOO0OOO0O0OOO00O0 ,OOOO0000O0OO000OO )#line:75
    shutil .move (OOO0OO0OOOO0O0OOO ,O0O00O00O00O0OOO0 )#line:76
    shutil .move (OO0O000O0OO00OOO0 ,O00O00O000O000000 )#line:77
    shutil .move (OO0OOO0000OOOOO0O ,OO0OOO0O0O0000O0O )#line:78
import requests #line:1
import json #line:2
import sys #line:3
import requests ,sys #line:4
import os ,time #line:5
from itertools import islice #line:6
import threading #line:7
from bs4 import BeautifulSoup #line:8
import pathlib #line:9
from colorama import init #line:10
from termcolor import colored #line:11
from colorama import Fore ,Back ,Style #line:12
init (autoreset =True )#line:13
from prx import prxgen #line:14
